name: church_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.1.0
  just_audio: ^0.9.14
  audio_service: ^0.18.1
  http: ^0.13.1
  agora_rtc_engine: ^4.0.6
  permission_handler: ^7.1.0
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  flutter_local_notifications: ^8.1.1+1
  firebase_auth: ^3.0.2
  provider: ^6.0.0
  social_share: ^2.1.1
  cached_network_image: ^3.1.0
  font_awesome_flutter: ^9.1.0
  flutter_cache_manager: ^3.1.2
  shared_preferences: ^2.0.7
  easy_localization: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  simple_speed_dial: ^0.1.3
  amplify_core: ^0.2.4
  amplify_auth_cognito: ^0.2.4
  amplify_storage_s3: ^0.2.4
  amplify_flutter: ^0.2.4
  get_it: ^7.2.0
  miniplayer: ^1.0.1
  audio_video_progress_bar: ^0.9.0
  url_launcher: ^6.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/kdec.png"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/translation/
    - images/kdec.png
    - images/podcast.jpg
    - images/album.jpg
    - images/background.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: ABEAKRG
      fonts:
        - asset: fonts/ABEAKRG.ttf
    - family: GESSTwo
      fonts:
        - asset: fonts/GESSTwoBold.otf
        - asset: fonts/GESSTwoMedium.otf
        - asset: fonts/GESSTwoLight.otf
